package com.cyb.authority.domain;

import lombok.Data;

@Data
public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sat May 04 15:08:34 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.name
     *
     * @mbg.generated Sat May 04 15:08:34 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.remarks
     *
     * @mbg.generated Sat May 04 15:08:34 CST 2019
     */
    private String remarks;

}