package com.cyb.authority.domain;

import lombok.Data;

@Data
public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.id
     *
     * @mbg.generated Sat May 04 15:10:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated Sat May 04 15:10:52 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission_id
     *
     * @mbg.generated Sat May 04 15:10:52 CST 2019
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.remarks
     *
     * @mbg.generated Sat May 04 15:10:52 CST 2019
     */
    private String remarks;

}